# =======================
#  Makefile for Tests
# ======================

$(info Compiling with $(CXX) using $(CPP_STD) flag)
all:
	make -s -C ./Test_clock_utils
#	./runTests

clean:
	@make clean -s -C ./Test_clock_utils

