# =======================
#  Makefile for Tpm_src
# ======================

all:
	make -s -C ./Ibmtss/Common
	make -s -C ./Ibmtss/Test/Test_wa_tpm

clean:
	@make clean -s -C ./Ibmtss/Common
	@make clean -s -C ./Ibmtss/Test/Test_wa_tpm
