# ===========================
#  Makefile for Ibmtss/Test
# ===========================

$(info Compiling with $(CXX) using $(CPP_STD) flag)

all:
	make -s -C ./Test_wa_tpm

clean:
	make clean -s -C ./Test_wa_tpm


